name: DutyManager
version: 1.1
main: me.cyph3er.dutymanager.DutyManager
api-version: 1.18

commands:
  duty:
    description: Opens the staff duty panel
    usage: /duty
    permission: dutymanager.use
  dutylist:
    description: Displays a list of staff on duty
    usage: /dutylist
    permission: dutymanager.use
  dutytimes:
    description: Displays the staff's weekly duty time
    usage: /dutytimes
    permission: dutymanager.use

permissions:
  dutymanager.use:
    description: Allows use of commands and the duty panel
    default: op

  dutymanager.bypass.gamemode:
    description: Allows changing gamemode while on duty (for helpers)
    default: false